spring:
  profiles:
    active: local

server:
  port: 8080

---
spring.profiles: set1
spring.profiles.include:
  - real-db
  - real-cache

server:
  port: 8081
---
spring.profiles: set2
spring.profiles.include:
  - real-db
  - real-cache
server:
  port: 8081